# Generated by Django 5.2.6 on 2025-10-02 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Publicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='TB_CATEGORIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=50, verbose_name='NOME')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.area')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.instrutor')),
                ('publicos', models.ManyToManyField(to='core.publicos')),
            ],
        ),
        migrations.CreateModel(
            name='TB_PROJETOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=100, verbose_name='TITULO')),
                ('DESCRICAO', models.TextField(verbose_name='DESCRICAO')),
                ('CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_categorias')),
            ],
        ),
        migrations.CreateModel(
            name='TB_ALUNO',
            fields=[
                ('MATRICULA', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='MATRICULA')),
                ('NOME', models.TextField(verbose_name='MATRICULA')),
                ('EMAIL', models.TextField(verbose_name='EMAIL')),
                ('PROJETO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tb_projetos')),
            ],
        ),
    ]
